### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Wnde** [sdelgadoc/admingpt#2]
I get this error:
]$ python admingpt.py
Traceback (most recent call last):
  File "/home/sady/AdminGPT/admingpt.py", line 159, in <module>
    run(email_platform="outlook", debug=True)
  File "/home/sady/AdminGPT/admingpt.py", line 58, in run
    assistant = client.beta.assistants.create(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sady/.local/lib/python3.12/site-packages/openai/resources/beta/assistants/assistants.py", line 108, in create
    return self._post(
           ^^^^^^^^^^^
  File "/home/sady/.local/lib/python3.12/site-packages/openai/_base_client.py", line 1200, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sady/.local/lib/python3.12/site-packages/openai/_base_client.py", line 889, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/sady/.local/lib/python3.12/site-packages/openai/_base_client.py", line 980, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "The requested model 'gpt-4-1106-preview' does not exist.", 'type': 'invalid_request_error', 'param': 'model', 'code': 'model_not_found'}}

**Comment by sdelgadoc** [comment]
Thanks for using AdminGPT @Wnde! To use the Assistant API, you need access to GPT-4. The error tells us that the required model "gpt-4-1106-preview", doesn't exist and therefore is not available to you. I just double checked, and I had access to it.

Please find below a link to OpenAI's documentation on how to access GPT-4.

How can I access GPT-4?
https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4

Please follow the steps and let me know if it fixes your error.

**Comment by sdelgadoc** [comment]
Hey @Wnde, did you get this figured out? I wanted to see if I could help with anything, or if I should close the issue. Let me know!

**Comment by sdelgadoc** [comment]
Closing due to lack of feedback from the user.
